export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_FAILED = 'SERVICES_FAILED';
export const ADD_SERVICES = 'ADD_SERVICES';

export const ORGANIZATION_LOADING = 'ORGANIZATION_LOADING';
export const ORGANIZATION_FAILED = 'ORGANIZATION_FAILED';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';


export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';

export const SERVICETYPES_LOADING = 'SERVICETYPES_LOADING';
export const SERVICETYPES_FAILED = 'SERVICETYPES_FAILED';
export const ADD_SERVICETYPES = 'ADD_SERVICETYPES';


export const SERVICE_SUPPORT_CONTRACTS_LOADING = 'SERVICE_SUPPORT_CONTRACTS_LOADING';
export const SERVICE_SUPPORT_CONTRACTS_FAILED = 'SERVICE_SUPPORT_CONTRACTS_FAILED';
export const ADD_SERVICE_SUPPORT_CONTRACTS = 'ADD_SERVICE_SUPPORT_CONTRACTS';


export const USERS_BYDEPARTMENTID_LOADING = 'USERS_BYDEPARTMENTID_LOADING';
export const USERS_BYDEPARTMENTID_FAILED = 'USERS_BYDEPARTMENTID_FAILED';
export const ADD_USERS_BYDEPARTMENTID = 'ADD_USERS_BYDEPARTMENTID';

export const SERVICE_CATEGORIES_LOADING = 'SERVICE_CATEGORIES_LOADING';
export const SERVICE_CATEGORIES_FAILED = 'SERVICE_CATEGORIES_FAILED';
export const ADD_SERVICE_CATEGORIES = 'ADD_SERVICE_CATEGORIES';

